def generate_streamlit_app(intent, ui_schema):

    app_name = intent.app_name

    code = f'''
import streamlit as st

st.title("{app_name}")

st.write("Generated by AI App Compiler")

'''

    # Generate UI pages/components
    for page in ui_schema.pages:

        code += f'\nst.header("{page.name}")\n'

        for component in page.components:

            if "Grid" in component:
                code += '''
cols1 = st.columns(3)
cols2 = st.columns(3)
cols3 = st.columns(3)

for cols in [cols1, cols2, cols3]:
    for col in cols:
        col.button(" ")
'''

            else:
                code += f'\nst.write("{component}")\n'

    return code

