def render_component(component: str) -> str:
    c = component.lower()

    if "email" in c:
        return 'st.text_input("Email")\n'

    if "password" in c:
        return 'st.text_input("Password", type="password")\n'

    if "input" in c or "form" in c:
        return '''
with st.form("generated_form"):
    st.text_input("Name")
    st.text_input("Email")
    submitted = st.form_submit_button("Submit")
    if submitted:
        st.success("Form submitted successfully")
'''

    if "button" in c:
        return '''
if st.button("Action"):
    st.success("Action completed")
'''

    if "table" in c or "contact" in c or "list" in c:
        return '''
st.table([
    {"Name": "John Doe", "Email": "john@example.com", "Status": "Active"},
    {"Name": "Jane Smith", "Email": "jane@example.com", "Status": "Pending"}
])
'''

    if "chart" in c or "analytics" in c or "stats" in c:
        return '''
st.bar_chart({
    "Users": [10, 20, 30, 45],
    "Revenue": [5, 15, 25, 40]
})
'''

    if "grid" in c or "game" in c:
        return '''
st.write("### Game Grid")

for row in range(3):
    cols = st.columns(3)
    for col in cols:
        col.button(" ", key=f"cell_{row}_{cols.index(col)}")
'''

    if "sidebar" in c:
        return '''
st.sidebar.title("Navigation")
st.sidebar.radio("Go to", ["Dashboard", "Users", "Settings"])
'''

    if "navbar" in c:
        return 'st.write("### Navigation Bar")\n'

    if "message" in c or "result" in c:
        return 'st.info("Result or status message will appear here.")\n'

    return f'st.write("{component}")\n'


def generate_streamlit_app(intent, ui_schema):
    app_name = intent.app_name

    code = f'''
import streamlit as st

st.set_page_config(page_title="{app_name}", layout="wide")

st.title("{app_name}")
st.caption("Generated by AI App Compiler")

'''

    for page in ui_schema.pages:
        code += f'\nst.header("{page.name}")\n'

        for component in page.components:
            code += render_component(component)
            code += "\n"

    return code