
import streamlit as st

st.set_page_config(page_title="Tic Tac Toe Game", layout="wide")

st.title("Tic Tac Toe Game")
st.caption("Generated by AI App Compiler")


st.header("Home Screen")

st.write("### Game Grid")

for row in range(3):
    cols = st.columns(3)
    for col in cols:
        col.button(" ", key=f"cell_{row}_{cols.index(col)}")


if st.button("Action"):
    st.success("Action completed")


st.header("Game Screen")

st.write("### Game Grid")

for row in range(3):
    cols = st.columns(3)
    for col in cols:
        col.button(" ", key=f"cell_{row}_{cols.index(col)}")

st.write("Current Turn Indicator")


st.write("### Game Grid")

for row in range(3):
    cols = st.columns(3)
    for col in cols:
        col.button(" ", key=f"cell_{row}_{cols.index(col)}")


if st.button("Action"):
    st.success("Action completed")

