
import streamlit as st

st.set_page_config(page_title="Tic Tac Toe", layout="wide")

st.title("Tic Tac Toe")
st.caption("Generated by AI App Compiler")


st.header("Game Board")

st.write("### Game Grid")
for row in range(3):
    cols = st.columns(3)
    for col_index, col in enumerate(cols):
        col.button(" ", key=f"cell_{row}_{col_index}")

st.write("Player Turn Indicator")

st.write("Score Display")


st.header("Scoreboard")

st.table([
    {"Name": "John Doe", "Email": "john@example.com", "Status": "Active"},
    {"Name": "Jane Smith", "Email": "jane@example.com", "Status": "Pending"}
])

st.write("Player Rankings")


st.write("### Game Grid")
for row in range(3):
    cols = st.columns(3)
    for col_index, col in enumerate(cols):
        col.button(" ", key=f"cell_{row}_{col_index}")


st.header("Multiplayer Lobby")

st.table([
    {"Name": "John Doe", "Email": "john@example.com", "Status": "Active"},
    {"Name": "Jane Smith", "Email": "jane@example.com", "Status": "Pending"}
])


if st.button("Action"):
    st.success("Action completed")


if st.button("Action"):
    st.success("Action completed")

