
import streamlit as st

st.title("Tic Tac Toe")

st.write("Generated by AI App Compiler")


st.header("GameScreen")

cols1 = st.columns(3)
cols2 = st.columns(3)
cols3 = st.columns(3)

for cols in [cols1, cols2, cols3]:
    for col in cols:
        col.button(" ")

st.write("Game Status Display")

st.write("New Game Button")
